- pkg/remotewrite/config.go
- pkg/remotewrite/config_test.go
Add support for http headers so that  it can use cortex with the `auth_enabled` option
Signed-off-by: johncming <johncming@yahoo.com>
> Add http headers support for write api.

- pkg/remotewrite/config.go
- pkg/remotewrite/config_test.go
- pkg/remotewrite/labels.go
- pkg/remotewrite/labels_test.go
Since the URL tag can often have high cardinality this PR makes this Tag/Label optional following the same structure as the keepNameTag config setting. Default `true` for backwards compatibility.
This allows for a common URL Grouping pattern to be used as describe [here](https://k6.io/docs/using-k6/http-requests/#url-grouping) by setting ` K6_KEEP_URL_TAG=false` and `K6_KEEP_NAME_TAG=true`
Tests also added with the same format as name tag handling
> Add support for keepUrlTag

- .github/workflows/all.yml
Apparently, the `https://honnef.co/go/tools?go-get=1` is returning a `bad gateway` error, it's better to enable the goproxy so we can benefit from some caching in case of fault on the various provider.
It also upgrades the golanci-lint version
> Renabled the goproxy for the CI

- pkg/remotewrite/prometheus.go
Otherwise this information is lost when using prometheus.
> Send the trend count as a metric

- pkg/remotewrite/prometheus.go
- pkg/remotewrite/prometheus_test.go
Send the `sum` of values of a Trend metric to prometheus to allow the calculation of moving averages:
```
rate(http_request_duration_seconds_sum[2m]) / rate(http_request_duration_seconds_count[2m])
```
Signed-off-by: Pablo Chacin <pablochacin@gmail.com>
> Send trend sum as metric

- README.md
- pkg/remotewrite/config.go
- pkg/remotewrite/config_test.go
- pkg/remotewrite/remotewrite.go
- pkg/remotewrite/remotewrite_test.go
This PR includes changes for the config and the URL printing in the description.
Renamed for consistency the following env var options:
`K6_PROMETHEUS_FLUSH_PERIOD` => `K6_PROMETHEUS_PUSH_INTERVAL` (it aligns to the same name used by timescaledb, influxdb and statsd outputs).
`K6_PROMETHEUS_USER` => `K6_PROMETHEUS_USERNAME` (it aligns to the same name used by influxdb output).
Removed completely for aligning to what we are doing with other outputs the following options:
`KeepTags`, `KeepNameTag`, `KeepUrlTag`, as explained in https://github.com/grafana/xk6-output-prometheus-remote/issues/47, tags should be controlled by `systemTags` option or by the solution explained in https://github.com/grafana/xk6-output-prometheus-remote/issues/5 (TLDR; https://github.com/grafana/k6/issues/1321) when …
> Polish config

- pkg/remote/client.go
- pkg/remote/client_test.go
The remote-write specification doesn't define the expected status code. It extends the policy to all the successful status codes because it can't make assumptions. There are so many implementations and the protocol doesn't limit them to return any code.
e.g. Mimir uses a 200 OK as a response status code.
> Relax response status code policy

- pkg/remotewrite/config.go
- pkg/remotewrite/config_test.go
k6 doesn't have a defined way of providing Output options. Instead of adding one more way, we should define one standard for all of them and only after adopting it here.
> Drop options from cli argument

- pkg/remotewrite/remotewrite.go
- pkg/remotewrite/remotewrite_test.go
https://prometheus.io/docs/practices/naming/#metric-names
* Force `_total` suffix for the Counter type as suggested by the Prometheus and  OpenMetrics conventions.
* Force `_rate` suffix for the Rate type so it can be identified easier because they are converted into Gauges.
> Force the naming convention

- pkg/remotewrite/remotewrite.go
- pkg/remotewrite/remotewrite_test.go
Added a Stale marker at the end of the test for all the seen time series.  
Closes #68 #37
> Stale markers

- README.md
- docker-compose.yml
- pkg/remotewrite/config.go
- pkg/remotewrite/config_test.go
- pkg/remotewrite/remotewrite.go
- pkg/remotewrite/remotewrite_test.go
- register.go
It renames the registered name from `"output-prometheus-remote` to `xk6-prometheus-rw` and it makes the env vars consistent with the new name renaming the prefix to `K6_PROMETHEUS_RW_*`
> Rename from prometheus-remote to prometheus-rw

- .golangci.yml
- pkg/remote/client.go
- pkg/remote/client_test.go
- pkg/remotewrite/config.go
- pkg/remotewrite/config_test.go
- pkg/remotewrite/prometheus_test.go
- pkg/remotewrite/remotewrite.go
- pkg/remotewrite/remotewrite_test.go
- pkg/remotewrite/trend.go
- pkg/remotewrite/trend_test.go
- register.go
Here's a PR adding the k6 golangci-lint configuration to the repo and addressing the issues outlined by it. Note that in a bunch of places, I simply locally deactivated the lining rule as I was not 100% certain if things such as type casts being unchecked were intentional or not.
Let me know what you think, and if you spot things that could/should be done differently 🙇🏻
> Add k6's linting rules and address detected issues

- pkg/remote/client_test.go
- pkg/remotewrite/config.go
- pkg/remotewrite/config_test.go
- pkg/remotewrite/remotewrite.go
- pkg/remotewrite/remotewrite_test.go
- pkg/stale/stale.go
It introduces a new option `K6_PROMETHEUS_RW_STALE_MARKERS=<bool>` for enabling the Staleness marking process at the end of the test. It also disables the option by default.
> Stale marker option

- pkg/remotewrite/config.go
- pkg/remotewrite/config_test.go
There are no reasons to set it to true, the default server URL is HTTP based and if an HTTPS endpoint is added then the client validation is expected to happen with the default path.
> Not skip the TLS validation

- pkg/remote/client_test.go
- pkg/remotewrite/remotewrite.go
- pkg/remotewrite/remotewrite_test.go
- pkg/stale/stale.go
~~It introduces a new option `K6_PROMETHEUS_RW_STALE_MARKERS=<bool>` for enabling the Staleness marking process at the end of the test. It also disables the option by default.~~ Moved to https://github.com/grafana/xk6-output-prometheus-remote/pull/86
It adjusts the stale marker accuracy by adding slight padding.
> Stale marker accuracy

- pkg/remotewrite/prometheus.go
- pkg/remotewrite/prometheus_test.go
Labels with empty key or value are not allowed by the remote write spec, so if any seen tag contains them then they are not mapped to the related label.
Prometheus server automatically discards them but other remote write implementations return a validation error. (e.g. Thanos).
Credits to @afajl that reports the issue.
> Discard tags with empty fields

- grafana/dashboards/dashboard-tests.json
These values of datasource were hardcoded and does not use the variable.
> Add prometheus variable for datasource

- pkg/remotewrite/config.go
- pkg/remotewrite/config_test.go
Closes https://github.com/grafana/xk6-output-prometheus-remote/issues/101
> New format for custom HTTP headers

- pkg/remotewrite/config.go
- pkg/remotewrite/config_test.go
Closes https://github.com/grafana/xk6-output-prometheus-remote/issues/54
> Support Bearer Token

- grafana/dashboards/k6-prometheus-native-histogram.json
- grafana/dashboards/k6-prometheus.json
Fixes the `HTTP requests failures` panel (#152)
The public dashboards have also been updated:
- https://grafana.com/grafana/dashboards/19665-k6-prometheus/
- https://grafana.com/grafana/dashboards/18030-k6-prometheus-native-histograms/
> Dashboards: fix `HTTP request failures` counter

- pkg/remote/client.go
When trying to build for 32-bit ARM (linux/arm), you get:
```
pkg/remote/client.go:120:35: cannot use 0xffffffff (untyped int constant 4294967295) as int value in argument to fmt.Errorf (overflows)
```
Pass the constant as unsigned 64-bit integer, which is what the underlying snappy code is doing (it's casting the argument to an uint64 and comparing against 0xffffffff, which in Go means it's comparing against uint64(0xffffffff)). Since this is just an error message, it shouldn't matter, but let's be consistent.
> Fix 32-bit build

- grafana/dashboards/k6-prometheus.json
- Add a fix to the Peak RPS calculation by adding the Reduce (to max) transformation.
- Set shared tooltip in the Performance Overview panel
- Calculate the number of VUs by summing instead of average as it might mislead if you're testing with multiple instances. In our case 4 nodes, each 250 VUs. Previously this would have been displayed as 250 instead of 1000.
> Fix Peak RPS calculation, shared tooltip and fix VU display in the Performance Overview 

- pkg/remote/client.go
- pkg/remotewrite/config.go
- pkg/sigv4/const.go
- pkg/sigv4/sigv4.go
- pkg/sigv4/sigv4_test.go
- pkg/sigv4/tripper.go
- pkg/sigv4/tripper_test.go
- pkg/sigv4/util_test.go
- pkg/sigv4/utils.go
- Added Tripper to enable signing requests
- Added Signer to implement the AWS sigv4 signing standard
I based my PR on this comment https://github.com/grafana/xk6-output-prometheus-remote/pull/161#issuecomment-1934440630 and  https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html
Note: I don't have deep knowledge about the sigv4, so please provide as much feedback as possible, and I will be happy to address it :) 
Addresses: https://github.com/grafana/xk6-output-prometheus-remote/issues/93
> feat: support sigv4 signing

- pkg/remotewrite/config.go
This is a temporary omitting of the linter issue; in the future, we should refactor this method.
Triggered after https://github.com/grafana/xk6-output-prometheus-remote/pull/169, but not caused.
To make CI green again.
> Omit parseEnvs linter issue

- grafana/dashboards/k6-prometheus.json
This pull request updates the k6-prometheus.json file for the K6 Prometheus dashboard. Specifically, I’ve changed the aggregation method in the Requests by URL panel to use lastNotNull for quantile calculations. Previously, the aggregation used mean, which caused the dashboard to not match the K6 console output.
I discovered this issue while comparing the K6 console output and the Grafana dashboard and also discussed it in this [Grafana forum post](https://community.grafana.com/t/discrepancy-between-k6-console-output-and-grafana-dashboard-for-p90-p95-metrics/133602).
The problem was that the dashboard used the mean aggregation for quantiles, leading to discrepancies, particularly in cases where URL request durations varied more significantly.
By switching to the lastNotNull aggregation …
> Fix K6 Prometheus Dashboard Metrics Quantile Mismatch by Changing Aggregation to lastNotNull

- README.md
Warn users that we no longer accept contributions to the repository.
It has been merged to the core https://github.com/grafana/k6/pull/4519
> Warning that repositopry in no longer maintained
